### ISSUE TITLE
ATTENDEE cut between email with new line - can´t parse

### ISSUE THREAD

**Issue by benjamin79** [lpil/icalendar#12]
Hi,

Outlook 2016 generated the following 2 lines in an ics:

ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=someone
 @gmail.com:MAILTO:someone@gmail.com

Problem: Parser sees it as 2 lines and not 1.

How can ATTENDEE be parsed?

thanks

**Comment by lpil** [comment]
Thanks!

**Comment by benjamin79** [comment]
Any update on this? I can´t solve it myself.

**Comment by lpil** [comment]
Perhaps you could open a PR with a failing unit test? That would help :)

**Comment by ericdude4** [comment]
For future reference, "unfold" your ics string with `String.replace(ics_string, "\n ", "")` before calling the `ICalendar.Deserialize.from_ics/1`

Read more [here (4.1 Content Lines)](http://www.ietf.org/rfc/rfc2445.txt)

**Comment by ericdude4** [comment]
@lpil This can be closed

**Comment by lpil** [comment]
Thank you
