### ISSUE TITLE
Change naming conventions to 'encode/decode'

### ISSUE THREAD

**Issue by pinx** [lpil/icalendar#23]
In some communities, people talk about serializing and deserializing. It seems that in the Elixir (and also Elm) community, people tend to talk/write about encoding and decoding into and out of strings/iodata.

The ICalendar can be used similarly to the Poison library. Maybe it would be a good idea to switch to the same vocabulary.  
NB: "Poison.Encoder" smells like OO, so I propose the Elm convention of an Encode and a Decode module.

**Comment by lpil** [comment]
If we were starting today I'd agree, but we're two years in (to the day :birthday:) and this doesn't seem worth disturbing all the users with a breaking change.
