### ISSUE TITLE
Outlook generated timezone can´t be parsed

### ISSUE THREAD

**Issue by benjamin79** [lpil/icalendar#25]
DTSTART;TZID=W. Europe Standard Time:20181227T130000 or
DTSTART;TZID="W. Europe Standard Time":20181227T130000

leads to 

```
** (MatchError) no match of right hand side value: {:error, "Expected end of input at line 1, column 17"}
    (icalendar) lib/icalendar/util/deserialize.ex:66: ICalendar.Util.Deserialize.parse_attr/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
```

Reason seems to be the missing lookup:
https://github.com/bitwalker/timex/blob/master/priv/standard_to_olson.exs

I´m not sure where and how to do it, but there needs be something like this:
Timex.Timezone.Utils.to_olson("W. Europe Standard ") which replaces it with "Europe/Berlin"

**Comment by ericdude4** [comment]
@benjamin79 Thanks for your tip on the standard_to_olson.exs file. This is now supported in https://github.com/lpil/icalendar/pull/36

**Comment by ericdude4** [comment]
@lpil I think this issue can be closed

**Comment by lpil** [comment]
Thank you
