### ISSUE TITLE
Support sequence number

### ISSUE THREAD

**Issue by jgautsch** [lpil/icalendar#35]
Per this [SO answer](https://stackoverflow.com/questions/10551764/how-to-cancel-an-calendar-event-using-ics-files/10561761)- SEQUENCE can be used in conjunction with UID in order to cancel previously sent ICS events.

I'm happy to submit a PR.

Reference: https://tools.ietf.org/html/rfc5545#section-3.8.7.4

**Comment by lpil** [comment]
Sounds useful. How would you envision it working in this library?

**Comment by ericdude4** [comment]
@jgautsch supported in https://github.com/lpil/icalendar/pull/36

**Comment by ericdude4** [comment]
@lpil This issue can be closed

**Comment by lpil** [comment]
Thank you
