### ISSUE TITLE
Empty param values in a VEVENT crash deserializer

### ISSUE THREAD

**Issue by ericdude4** [lpil/icalendar#38]
An event with

`X-APPLE-STRUCTURED-LOCATION;X-ADDRESS=;X-TITLE=Paris:geo:48.856788,2.351077`

will crash the deserializer with the following error:

`** (MatchError) no match of right hand side value: ["X-ADDRESS"]
    (icalendar) lib/icalendar/util/deserialize.ex:60: anonymous fn/2 in ICalendar.Util.Deserialize.retrieve_params/1`

**Comment by lpil** [comment]
Thanks for the report and the PR, I've left a comment.
