### ISSUE TITLE
How to add custom fields?

### ISSUE THREAD

**Issue by bfontaine** [lpil/icalendar#52]
Hello and thank you for this library. I would like to add custom fields, such as `X-APPLE-STRUCTURED-LOCATION`. Is there some way that I overlooked, or should I manipulate the ics string to inject the field?
Thanks

**Comment by lpil** [comment]
I don't believe we have any API for doing this presently.

**Comment by bfontaine** [comment]
Thanks. Do you think adding an attribute with a map for extra fields would make sense?

**Comment by lpil** [comment]
Sure, but we would need to ensure that any API we offer is spec compliant.

**Comment by bfontaine** [comment]
In the meantime I abandonned the project I needed this for, so I’m closing this.
